global:
  qsname: qs_puppet
  qsenv: dev
  reporting: true
  cis3bucket:  s3://quickstart-ci-bucket
  regions:
    - us-east-1

tests:
  qs_puppet:
    template_file: Puppet-QuickStart.template
    parameter_input: Puppet-QuickStart.json
